# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-09-09 11:18
from __future__ import unicode_literals

import crm.models
import crm.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing_Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='marka')),
                ('family', models.CharField(max_length=50, verbose_name='rodzina')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('ear', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('current', models.BooleanField(default=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('our', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hearing_Aid_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='marka')),
                ('family', models.CharField(max_length=50, verbose_name='rodzina')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('added', models.DateField(default=datetime.datetime(2020, 9, 9, 11, 18, 24, 380004, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=True, verbose_name='aktualna')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='notatka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('audiometrist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFZ_Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('in_progress', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='nie podano', max_length=120)),
                ('phone_no', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('house_number', models.CharField(blank=True, max_length=6, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('NIP', models.CharField(blank=True, max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('requires_action', models.BooleanField(default=True)),
                ('audiometrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCPR_Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=True, verbose_name='aktualna')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='notatka')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=crm.models.in_60_days)),
                ('ha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Hearing_Aid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=crm.models.in_60_days)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_NFZ_Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=crm.models.in_60_days)),
                ('nfz_confirmed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.NFZ_Confirmed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_PCPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=crm.models.in_60_days)),
                ('pcpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PCPR_Estimate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SZOI_Errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_log', models.TextField()),
                ('line', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SZOI_File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', validators=[crm.validators.xls_only])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SZOI_File_Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.DateTimeField(auto_now_add=True)),
                ('szoi_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SZOI_File')),
            ],
        ),
        migrations.AddField(
            model_name='szoi_errors',
            name='szoi_file_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.SZOI_File_Usage'),
        ),
        migrations.AddField(
            model_name='nfz_confirmed',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='hearing_aid_stock',
            name='szoi_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_szoi_new', to='crm.SZOI_File_Usage'),
        ),
        migrations.AddField(
            model_name='hearing_aid_stock',
            name='szoi_updated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ha_szoi_updated', to='crm.SZOI_File_Usage'),
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.PCPR_Estimate'),
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Invoice'),
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
