# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2019-07-17 00:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrective_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=True, verbose_name='aktualna')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='notatka')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hearing_Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='marka')),
                ('family', models.CharField(max_length=50, verbose_name='rodzina')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cena brutto')),
                ('vat_rate', models.CharField(choices=[('zwolniona', 'zwolniona'), ('0', '0'), ('5', '5'), ('8', '8'), ('23', '23')], default='8', max_length=9, verbose_name='stawka VAT')),
                ('pkwiu_code', models.CharField(max_length=20, verbose_name='kod PKWiU')),
                ('ear', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('current', models.BooleanField(default=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('our', models.BooleanField(default=True)),
                ('corrective_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Corrective_Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hearing_Aid_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='marka')),
                ('family', models.CharField(max_length=50, verbose_name='rodzina')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cena brutto')),
                ('vat_rate', models.CharField(choices=[('zwolniona', 'zwolniona'), ('0', '0'), ('5', '5'), ('8', '8'), ('23', '23')], default='8', max_length=9, verbose_name='stawka VAT')),
                ('pkwiu_code', models.CharField(max_length=20, verbose_name='kod PKWiU')),
                ('added', models.DateField(default=datetime.date(2019, 7, 17))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=True, verbose_name='aktualna')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='notatka')),
                ('payed', models.BooleanField(default=False, verbose_name='zap\u0142acona')),
                ('type', models.CharField(choices=[('transfer', 'transfer'), ('cash', 'cash')], max_length=8, verbose_name='rodzaj p\u0142atno\u015bci')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('audiometrist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFZ_Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('in_progress', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NFZ_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('side', models.CharField(choices=[('left', 'left'), ('right', 'right')], max_length=5)),
                ('in_progress', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='marka')),
                ('family', models.CharField(max_length=50, verbose_name='rodzina')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cena brutto')),
                ('vat_rate', models.CharField(choices=[('zwolniona', 'zwolniona'), ('0', '0'), ('5', '5'), ('8', '8'), ('23', '23')], default='8', max_length=9, verbose_name='stawka VAT')),
                ('pkwiu_code', models.CharField(max_length=20, verbose_name='kod PKWiU')),
                ('corrective_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Corrective_Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Other_Item_Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='marka')),
                ('family', models.CharField(max_length=50, verbose_name='rodzina')),
                ('model', models.CharField(max_length=50, verbose_name='model')),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='cena brutto')),
                ('vat_rate', models.CharField(choices=[('zwolniona', 'zwolniona'), ('0', '0'), ('5', '5'), ('8', '8'), ('23', '23')], default='8', max_length=9, verbose_name='stawka VAT')),
                ('pkwiu_code', models.CharField(max_length=20, verbose_name='kod PKWiU')),
                ('added', models.DateField(default=datetime.date(2019, 7, 17))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='nie podano', max_length=120)),
                ('phone_no', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('house_number', models.CharField(blank=True, max_length=6, null=True)),
                ('apartment_number', models.CharField(blank=True, max_length=6, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=6, null=True)),
                ('NIP', models.CharField(blank=True, max_length=20, null=True)),
                ('audiometrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PCPR_Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('current', models.BooleanField(default=True, verbose_name='aktualna')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='notatka')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=datetime.date(2019, 9, 15))),
                ('ha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Hearing_Aid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=datetime.date(2019, 9, 15))),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Invoice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_NFZ_Confirmed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=datetime.date(2019, 9, 15))),
                ('nfz_confirmed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.NFZ_Confirmed')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_NFZ_New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=datetime.date(2019, 9, 15))),
                ('nfz_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.NFZ_New')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder_PCPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activation_date', models.DateField(default=datetime.date(2019, 9, 15))),
                ('pcpr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.PCPR_Estimate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='other_item',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.PCPR_Estimate'),
        ),
        migrations.AddField(
            model_name='other_item',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Invoice'),
        ),
        migrations.AddField(
            model_name='other_item',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='nfz_new',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='nfz_confirmed',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='estimate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.PCPR_Estimate'),
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Invoice'),
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AddField(
            model_name='corrective_invoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Invoice'),
        ),
        migrations.AddField(
            model_name='corrective_invoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
