# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 06:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 28, 6, 31, 48, 443000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
