# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_patient_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_no',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
