# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_patient_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField()),
                ('audiometrist', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
