# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20160702_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hearing_Aid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_make', models.TextField()),
                ('ha_family', models.TextField()),
                ('ha_model', models.TextField()),
                ('purchase_date', models.DateField()),
                ('ear', models.CharField(max_length=12)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient')),
            ],
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
