# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20160702_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing_aid',
            name='ha_family',
        ),
        migrations.RemoveField(
            model_name='hearing_aid',
            name='ha_make',
        ),
        migrations.RemoveField(
            model_name='hearing_aid',
            name='ha_model',
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='ha_name',
            field=models.CharField(default=datetime.datetime(2016, 7, 3, 10, 42, 54, 452000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hearing_aid',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AlterField(
            model_name='hearing_aid',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
