# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 06:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20160703_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hearing_aid',
            name='ha_name',
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='ha_family',
            field=models.CharField(default=datetime.datetime(2016, 7, 23, 6, 0, 14, 582000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='ha_make',
            field=models.CharField(default=datetime.datetime(2016, 7, 23, 6, 0, 33, 181000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hearing_aid',
            name='ha_model',
            field=models.CharField(default=datetime.datetime(2016, 7, 23, 6, 0, 47, 106000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hearing_aid',
            name='ear',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='hearing_aid',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
