# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_auto_20160802_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='HA_Invoice',
            fields=[
                ('hearing_aid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crm.Hearing_Aid')),
                ('date', models.DateField()),
                ('in_progress', models.BooleanField(default=True)),
            ],
            bases=('crm.hearing_aid',),
        ),
        migrations.AlterField(
            model_name='hearing_aid',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AlterField(
            model_name='newinfo',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
        migrations.AlterField(
            model_name='nfz_confirmed',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Patient'),
        ),
    ]
